### ISSUE TITLE
Worth checking

### ISSUE THREAD

**Issue by pdaengeli** [pdaengeli/iiif-servers#1]
* [loris-redux](https://github.com/jpstroop/loris-redux)

**Comment by dmj** [comment]
You might also add https://github.com/dmj/php-iiif-image-server -- It supports Image API 2.1 up to compliance level 2 and is implemented in PHP. The image transformations are done with PHP's libgd extensions. We used it as stub in our IIIF Pilot until we get JPEG2000 under control.
